const KEY='pao_na_porta_v1';
let db=JSON.parse(localStorage.getItem(KEY)||'{"clients":[],"sales":[]}');
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
let screen='home'; let deferredPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').hidden=false});
document.getElementById('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}};
const brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const dateBR=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR');
const today=()=>new Date().toISOString().slice(0,10);
const monthKey=d=>d.slice(0,7);
const client=id=>db.clients.find(c=>c.id===id);
function nav(){document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.screen===screen));}
function render(){nav(); const c=document.getElementById('content'); if(screen==='home')c.innerHTML=home(); if(screen==='clients')c.innerHTML=clients(); if(screen==='sales')c.innerHTML=sales(); if(screen==='receivables')c.innerHTML=receivables(); if(screen==='deliveries')c.innerHTML=deliveries(); bind();}
document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>{screen=b.dataset.screen;render()});
function home(){const t=today(), ds=db.sales.filter(s=>s.deliveryDate===t), due=db.sales.filter(s=>s.payment==='prazo'&&s.status!=='paid'); const todayTotal=db.sales.filter(s=>s.date===t).reduce((a,s)=>a+s.total,0); const overdue=due.filter(s=>s.dueDate<t).reduce((a,s)=>a+s.total,0);return `<section class="hero"><h2>Bom dia! 🥖</h2><div class="muted">Controle simples das vendas e entregas de pão.</div><div class="actions"><button class="btn primary" data-action="newSale">＋ Nova venda</button><button class="btn secondary" data-action="newClient">＋ Cliente</button></div></section><div class="grid"><div class="stat">Vendas hoje<b>${brl(todayTotal)}</b></div><div class="stat">Entregas<b>${ds.length}</b></div><div class="stat">A receber<b>${brl(due.reduce((a,s)=>a+s.total,0))}</b></div><div class="stat">Vencido<b>${brl(overdue)}</b></div></div><div class="card"><div class="row"><h3>Próximas entregas</h3><button class="btn secondary" data-screen2="deliveries">Ver todas</button></div>${ds.slice(0,5).map(deliveryRow).join('')||'<div class="empty">Nenhuma entrega para hoje.</div>'}</div>`}
function clients(){return `<div class="row"><div><h2>Clientes</h2><div class="muted">Nome, telefone e endereço.</div></div><button class="btn primary" data-action="newClient">＋</button></div>${db.clients.map(c=>`<div class="card"><div class="row"><div><h3>${esc(c.name)}</h3><div>${esc(c.phone)}</div><div class="muted">${esc(c.address)}</div></div><button class="btn secondary" data-edit-client="${c.id}">Editar</button></div></div>`).join('')||'<div class="empty">Cadastre o primeiro cliente.</div>'}`}
function sales(){return `<div class="row"><div><h2>Vendas</h2><div class="muted">Histórico das vendas lançadas.</div></div><button class="btn primary" data-action="newSale">＋</button></div>${db.sales.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(s=>{const c=client(s.clientId);return `<div class="card"><div class="row"><div><h3>${esc(c?.name||'Cliente removido')}</h3><div>${s.quantity} pão(ões) • ${s.type==='acucar'?'Com açúcar':'Sem açúcar'}</div><div class="muted">Venda ${dateBR(s.date)} • Entrega ${dateBR(s.deliveryDate)}</div></div><div class="money">${brl(s.total)}</div></div><div class="actions"><span class="pill">${s.payment==='avista'?'À vista':'A prazo'}</span>${s.payment==='prazo'?`<span class="pill ${s.status==='paid'?'green':s.dueDate<today()?'red':'gold'}">${s.status==='paid'?'PAGO':'Vence '+dateBR(s.dueDate)}</span>`:''}<span class="pill">${s.place==='trabalho'?'🏢 Trabalho':'🏠 Casa'}</span></div></div>`}).join('')||'<div class="empty">Nenhuma venda lançada.</div>'}`}
function receivables(){const groups={};db.sales.filter(s=>s.payment==='prazo').forEach(s=>{const k=s.clientId+'|'+monthKey(s.dueDate);(groups[k]??=[]).push(s)});return `<h2>Contas a receber</h2><div class="muted">Vendas a prazo agrupadas por cliente e mês.</div>${Object.entries(groups).sort((a,b)=>b[0].localeCompare(a[0])).map(([k,arr])=>{const c=client(arr[0].clientId), total=arr.reduce((x,s)=>x+s.total,0), paid=arr.every(s=>s.status==='paid'), due=arr[0].dueDate;return `<div class="card"><div class="row"><div><h3>${esc(c?.name||'Cliente')}</h3><div>${arr.length} venda(s) • fechamento ${monthKey(due)}</div></div><div class="money">${brl(total)}</div></div><div class="actions"><span class="pill ${paid?'green':due<today()?'red':'gold'}">${paid?'PAGO':due<today()?'VENCIDO':'A VENCER'}</span><span class="muted">Vencimento ${dateBR(due)}</span></div><div class="actions">${!paid?`<button class="btn success" data-pay-group="${k}">✓ Marcar pago</button>`:''}${!paid&&due<today()?`<button class="btn primary" data-whats-group="${k}">💬 Enviar WhatsApp</button>`:''}</div></div>`}).join('')||'<div class="empty">Nenhuma venda a prazo.</div>'}`}
function deliveries(){const t=today(), arr=db.sales.filter(s=>s.deliveryDate===t);return `<div class="row"><div><h2>Entregas de hoje</h2><div class="muted">${arr.length} entrega(s) programada(s).</div></div><button class="btn primary" data-action="openRoute">🗺️ Rota</button></div><div class="notice">Toque no endereço para abrir a navegação. A otimização automática por proximidade pode ser adicionada ao conectar um serviço de mapas.</div>${arr.map(deliveryRow).join('')||'<div class="empty">Nenhuma entrega para hoje.</div>'}`}
function deliveryRow(s){const c=client(s.clientId);return `<div class="card"><div class="row"><div><h3>${esc(c?.name||'Cliente')}</h3><div>${s.quantity} pão(ões) • ${s.type==='acucar'?'Com açúcar':'Sem açúcar'} • ${s.place==='trabalho'?'🏢 Trabalho':'🏠 Casa'}</div><div class="muted">${esc(c?.address||'')}</div></div><a class="btn secondary map" target="_blank" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(c?.address||'')}">📍</a></div></div>`}
function modal(html){document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
function newClient(existing){modal(`<button class="close" data-close>✕</button><h2>${existing?'Editar':'Novo'} cliente</h2><form id="clientForm"><div class="field"><label>Nome</label><input id="cn" required value="${esc(existing?.name||'')}"></div><div class="field"><label>Telefone</label><input id="cp" required inputmode="tel" placeholder="(00) 00000-0000" value="${esc(existing?.phone||'')}"></div><div class="field"><label>Endereço de entrega</label><input id="ca" required placeholder="Rua, número, bairro, cidade" value="${esc(existing?.address||'')}"></div><button class="btn primary full">Salvar cliente</button></form>`);document.getElementById('clientForm').onsubmit=e=>{e.preventDefault();const o={id:existing?.id||crypto.randomUUID(),name:cn.value.trim(),phone:cp.value.trim(),address:ca.value.trim()};if(existing)db.clients=db.clients.map(x=>x.id===o.id?o:x);else db.clients.push(o);save();closeModal();render()}}
function newSale(){if(!db.clients.length){alert('Cadastre um cliente primeiro.');screen='clients';render();return}modal(`<button class="close" data-close>✕</button><h2>Nova venda 🥖</h2><form id="saleForm"><div class="field"><label>Cliente</label><select id="sc" required>${db.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="two"><div class="field"><label>Tipo</label><select id="st"><option value="acucar">Com açúcar</option><option value="sem_acucar">Sem açúcar</option></select></div><div class="field"><label>Quantidade</label><input id="sq" type="number" min="1" value="1" required></div></div><div class="two"><div class="field"><label>Valor unitário (R$)</label><input id="su" type="number" min="0" step="0.01" required></div><div class="field"><label>Data da venda</label><input id="sd" type="date" value="${today()}" required></div></div><div class="two"><div class="field"><label>Data da entrega</label><input id="sdd" type="date" value="${today()}" required></div><div class="field"><label>Onde entregar</label><select id="sp"><option value="casa">🏠 Casa</option><option value="trabalho">🏢 Trabalho</option></select></div></div><div class="field"><label>Pagamento</label><select id="sPay"><option value="avista">À vista</option><option value="prazo">A prazo</option></select></div><div class="field" id="dueWrap" style="display:none"><label>Data para pagamento</label><input id="sDue" type="date"></div><div class="notice">Valor total: <b id="stotal">R$ 0,00</b></div><button class="btn primary full">Lançar venda</button></form>`);const upd=()=>stotal.textContent=brl((+sq.value||0)*(+su.value||0));sq.oninput=upd;su.oninput=upd;sPay.onchange=()=>{dueWrap.style.display=sPay.value==='prazo'?'block':'none';sDue.required=sPay.value==='prazo'};document.getElementById('saleForm').onsubmit=e=>{e.preventDefault();const total=(+sq.value||0)*(+su.value||0);db.sales.push({id:crypto.randomUUID(),clientId:sc.value,type:st.value,quantity:+sq.value,unit:+su.value,total,date:sd.value,deliveryDate:sdd.value,place:sp.value,payment:sPay.value,dueDate:sPay.value==='prazo'?sDue.value:sd.value,status:sPay.value==='prazo'?'open':'paid'});save();closeModal();render()}}
function groupByKey(k){return db.sales.filter(s=>s.clientId+'|'+monthKey(s.dueDate)===k)}
function bind(){document.querySelectorAll('[data-action="newClient"]').forEach(x=>x.onclick=()=>newClient());document.querySelectorAll('[data-action="newSale"]').forEach(x=>x.onclick=()=>newSale());document.querySelectorAll('[data-edit-client]').forEach(x=>x.onclick=()=>newClient(client(x.dataset.editClient)));document.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal);document.querySelectorAll('[data-screen2]').forEach(x=>x.onclick=()=>{screen=x.dataset.screen2;render()});document.querySelectorAll('[data-pay-group]').forEach(x=>x.onclick=()=>{groupByKey(x.dataset.payGroup).forEach(s=>s.status='paid');save();render()});document.querySelectorAll('[data-whats-group]').forEach(x=>x.onclick=()=>{const a=groupByKey(x.dataset.whatsGroup),c=client(a[0].clientId),total=a.reduce((n,s)=>n+s.total,0);const phone=(c?.phone||'').replace(/\D/g,'');const text=`Tudo bem ${c?.name||''}, tem uma notinha sua aqui, são ${brl(total)}. Consegue mandar pix pra mim?`;window.open(`https://wa.me/55${phone}?text=${encodeURIComponent(text)}`,'_blank')});document.querySelector('[data-action="openRoute"]')?.addEventListener('click',()=>{const arr=db.sales.filter(s=>s.deliveryDate===today());if(!arr.length)return;const addresses=arr.map(s=>client(s.clientId)?.address).filter(Boolean);const url='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(addresses[addresses.length-1])+'&waypoints='+encodeURIComponent(addresses.slice(0,-1).join('|'));window.open(url,'_blank')})}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
render();

if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
